### ISSUE TITLE
Array can no longer implement PLUS

### ISSUE THREAD

**Issue by mlms13** [Risto-Stevcev/bs-abstract#20] opened 2020-01-31 21:16 UTC
The upcoming version of Bucklescript changes the signature of `[||]` from `array('a)` to `array('_weak)` since there were unsoundness issues with `Js.Array.push`. This change makes `array` incompatible with the `PLUS` and `MONOID_ANY` typeclasses.

I'll open a PR removing the array implementation of `PLUS`, at least until we can come up with a better solution, assuming (maybe optimistically) that one exists. This will be a (pretty big) breaking change, but `bs-abstract` can't currently be built with the latest Bucklescript, so I'm not really sure what else to do. :confused:

**Comment by gaku-sei** [comment] 2020-02-01 09:11
An other way (also a breaking change) would be to wrap the implementation of PLUS in a functor :

```reason
module Plus = (Type: Interface.TYPE): PLUS with type t(Type.t) = array(Type.t) => {...}
```

This would make the use or Arrays' PLUS fonctions rather cumbersome though 😕

**Comment by gaku-sei** [comment] 2020-02-01 10:48
This compiles:

```reason
// I had to "mimic" the new behavior of the array type by using a ref here
type array'('a) = ref(array('a));

module ImmutableArray = {
  type t(+'a); // Uses the relaxed value restriction

  // Obj.magic makes sense here, we do want to have the same value, but don't want to add any constructor at runtime
  let from: array'('a) => t('a) = xs => Obj.magic(xs^);
};

// Dumb implementation
module Functor:
  BsAbstract.Interface.FUNCTOR with type t('a) = ImmutableArray.t('a) = {
  type t('a) = ImmutableArray.t('a);

  let map = Obj.magic;
};

// Dumb implementation
module Alt: BsAbstract.Interface.ALT with type t('a) = ImmutableArray.t('a) = {
  include Functor;

  let alt = Obj.magic;
};

module Plus: BsAbstract.Interface.PLUS with type t('a) = ImmutableArray.t('a) = {
  include Alt;

  // Magic!
  let empty = ImmutableArray.from(ref([||]));
};
```

**Comment by Risto-Stevcev** [comment] 2020-02-09 21:42
That sucks, that deviates from how native ocaml works right? :slightly_frowning_face:

Yeah I guess we could add an immutable array type and avoid adding in the mutable operations like `push` similar to what purescript does. My take is something like:

```ocaml
module ImmutableArray: sig
  type 'a t = private 'a array

  val empty: unit -> 'a t
  val pure: 'a -> 'a t
  val from_list: 'a list -> 'a t
end = struct
  type 'a t = 'a array

  let empty () = [||]
  let pure x = [|x|]
  let from_list = Array.of_list
  (* ... all the implementations including PLUS *)
end

module TestImmutableArray = struct
  let f (x: 'a array) = ignore x
  let foo = ImmutableArray.pure 123
  let _ = f (foo : int ImmutableArray.t :> int array)
end
```

What do you guys think?

**Comment by johnhaley81** [comment] 2020-02-10 00:38
`ImmutableArray` sounds like a great way forward to me.

**Comment by gaku-sei** [comment] 2020-02-10 02:26
Genuine question @Risto-Stevcev, how making the "alias" private solves the weak polymorphism issue here?

A fast and dirty implementation still raises the weak polymorphism "error" 😞 

```reason
module ImmutableArray: {
  type t('a) = pri array('a);

  let empty: unit => t('a);
  let pure: 'a => t('a);
  let fromList: list('a) => t('a);
} = {
  type t('a) = array('a);

  let empty = () => [||];
  let pure = x => [|x|];
  let fromList = Belt.List.toArray;

  open Interface;

  module Functor: FUNCTOR with type t('a) = t('a) = {
    type nonrec t('a) = t('a);
    let map = Obj.magic;
  };

  module Alt: ALT with type t('a) = t('a) = {
    include Functor;
    let alt = Obj.magic;
  };

  module Plus: PLUS with type t('a) = t('a) = {
    include Alt;
    let empty = empty();
  };
};
```

**Comment by gaku-sei** [comment] 2020-02-10 02:29
@cristianoc's implementation for ImmutableArray is also interesting: https://github.com/cristianoc/genType/blob/master/examples/flow-react-example/src/ImmutableArray.re

The only downside being the runtime cost 😕

**Comment by Risto-Stevcev** [comment] 2020-02-10 11:35
@gaku-sei You would only be able to contruct `ImmutableArray` using the `empty`, `pure` and `fromList` functions in the impl, so it wouldn't have `push` or any of the mutable stuff that makes it weak. You can upcast it to `array` but then it wouldn't be an `ImmutableArray` anymore

**Comment by gaku-sei** [comment] 2020-02-10 12:25
But since it relies on the array type which is weakly polymorphic at the compiler level, it seems that the weakly polymorphism would still strike when implementing Plus 😕  (I actually got the same error again).

Not related, but I wonder how the native OCaml compiler can make something like https://github.com/BuckleScript/bucklescript/issues/4087#issue-548619028 safe without a weakly polymorphic type actually 🤔

**Comment by flash-gordon** [comment] 2020-02-10 12:27
@gaku-sei it just doesn't have such API AFAIK, arrays are fixed in size

**Comment by gaku-sei** [comment] 2020-02-10 12:28
@flash-gordon , thanks ! That explains a lot ^^

**Comment by cristianoc** [comment] 2020-02-10 12:49
Btw we're not talking about immutable arrays here, just non-extensible arrays.
The only operation that creates trouble is array extension. So a version of arrays without that single operation is all one needs. No need for all the changes in ImmutableArray.

Now, to preserve non-extensibility, one would still have to deep-copy both ways between ordinary and extensible arrays.
But I guess, and might be wrong here, but if all you care about is type safety, then three might be a single dangerous conversion: from an empty non-exensible array to an ordinary one. So the conjecture is that one could make a conversion that is nearly always the identity function, except it needs to check if the array is empty. If it is, it could throw an exception, or make a copy. For the conversion from ordinary to non-extensible, the identity would do. I have not checked that this conversion is OK for type safety, so take it with a grain of salt.

**Comment by gaku-sei** [comment] 2020-02-10 13:32
`Btw we're not talking about immutable arrays here, just non-extensible arrays.`, yes that's what I noticed when comparing with native OCaml (thanks to @flash-gordon). And my first intuition seems to be correct: the `push` function is apparently the reason why arrays are weakly polymorphic in BuckleScript.

That being said, having an immutable array type is not only a way to solve the weakly polymorphic issue, it's also a feature request 😄 

Also, aside from solving the original issue, and unlike immutable arrays, having non-extensible arrays doesn't seem to bring anything new, but I might be wrong here. This type doesn't really exist in JavaScript, and the OCaml type system is not powerful enough to get any benefit from this type (unlike, say, [Idris'](https://github.com/idris-lang/Idris-dev/blob/master/libs/base/Data/Vect.idr)).

**Comment by Risto-Stevcev** [comment] 2020-02-10 17:10
Yeah we could add `StrongArray` as well and one of these for array access, but for some reason I can't get it working with bucklescript:
https://caml.inria.fr/pub/docs/manual-ocaml/manual042.html

**Comment by austindd** [comment] 2020-02-10 21:09
I ran into this today :/ .

So, based on a bit of reading, the issue is that you can specify an empty array with an array literal symbol, and it's not clear what the inner type of that array will be. Then, later, the push function can be applied to any generic array (in JS), at which point the type should be inferred by the compiler, since the element being "pushed" must match the array's inner type. But for some reason it is not inferred. Why is this an issue for the compiler?

**Comment by Risto-Stevcev** [comment] 2020-02-11 02:14
Yeah that's why it's value restricted now, because it's basically the same issue as `ref`. The functor can be added as well, it doesn't have to be either/or imo. It kind of sucks that this happened, oh well :slightly_frowning_face:

**Comment by gaku-sei** [comment] 2020-02-11 09:09
@Risto-Stevcev, unfortunately it seems that Reason doesn't support the custom syntax operators yet: https://github.com/facebook/reason/issues/2432. But since the `[]` and `[]=` operators just compile down to `Array.get` and `Array,get` respectively, one can just "override" these functions. Not super great though 😕

**Comment by gaku-sei** [comment] 2020-02-24 07:02
Sorry to ping, but is there any consensus reached for that one?

**Comment by Risto-Stevcev** [comment] 2020-02-25 12:54
Vote with emojis maybe? you can choose multiple:

1️⃣ Functor
2️⃣ ImmutableArray
3️⃣ StrongArray

**Comment by mlms13** [comment] 2020-02-25 17:27
I'd probably vote for `StrongArray` as it's the most "in the spirit of" JS arrays, without introducing un-soundness. But I don't really have a strong opinion, as our codebase relies much more heavily on lists than arrays.

Sadly, I don't think we can add arbitrary emoji responses to your post, but I'll stick my :three: here.

**Comment by yawaramin** [comment] 2020-02-25 18:16
There is another option, wait for BuckleScript release the 'unsafe array' flag and use that: https://github.com/BuckleScript/bucklescript/issues/4189

**Comment by flash-gordon** [comment] 2020-02-25 18:38
@yawaramin it's not a solution I would say. I would expect this flag to present only in BS 7.x then BS 8.x should either simply remove it or make empty arrays polymorphic again and rename `Js.Array.push` to `Js.Array.unsafePush` /cc @bobzhang

**Comment by yawaramin** [comment] 2020-02-25 19:39
Technically, BS 8 would be a major version update and we should expect some backward-incompatible changes. The hypothetical change you described, to remove the flag and make empty array literals strongly typed again, would not affect bs-abstract anyway–except for removing the build flag.

**Comment by bobzhang** [comment] 2020-02-26 01:24
> There is another option, wait for BuckleScript release the 'unsafe array' flag and use that: [BuckleScript/bucklescript#4189](https://github.com/BuckleScript/bucklescript/issues/4189)

Hi, we will add this flag to make time for transition. 
But in the long run, we will keep the empty array non-polymorphic. 
Since `push` is widely used, and the JS code may push elements on their side which is hard to detect. The tradeoff is not just removing push, but you also has to design an abstract vector type for the FFI

**Comment by yawaramin** [comment] 2020-02-26 03:19
Thanks @bobzhang that does make sense.

I do think, though, there would not be much use in the bs-abstract library defining a new immutable vector type to implement the `PLUS` type class while everyone else is using bare arrays. Anyone who would want to use this `PLUS` instance would need to convert back and forth between arrays and the new immutable vector type.

It would be another matter if the BuckleScript user community in general was encouraged to use a new, general-purpose immutable vector type that shipped in Belt, perhaps. Then bs-abstract would simply be providing instances for that general-purpose type.

**Comment by gaku-sei** [comment] 2020-02-26 06:48
@yawaramin having the two types in BuckleScript would indeed be the best option, `Js.Array.t('_weak) = array('_weak)` and `Belt.StrongArray.t('a)`, but conversion between the two would still be needed.

An other option would be to have a ppx or a literal for these types, `[|1, 2|]` for array and `[strong|1, 2|strong]` (or whatever) for strong array would help. Not sure @bobzhang would be in for this kind of things though ^^

@Risto-Stevcev I would say 1 (functors) if technically possible. Otherwise maybe 0: just drop the failing code for now, waiting for an other solution (unsafe array flag in BS, strong arrays, etc...).
I like the immutable arrays, but it feels like it doesn't belong to BsAbstract, maybe more to Relude or an other higher level library.

**Comment by Risto-Stevcev** [comment] 2020-02-27 09:14
Ok then I'll go with 0 for now and do nothing

**Closed by Risto-Stevcev** 2020-02-27 09:14 UTC
